# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Statistical Computing for Bayesian Inference and Forecasting
email: jacobcvt12@gmail.com
description: A blog about Bayesian statistics with an emphasis on computational challenges
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  jacobcvt12

# Build settings
markdown: kramdown
